### PR TITLE
Split files and dateonly

### PR DESCRIPTION
**Pull request by jods4**
This is the same PR as #50.
Github didn't seem to be pulling my last commit in the PR, for some reason :(

### CODE REVIEW

**Comment by jods4** [comment]
Some tests fail but it looks like they were failing before my PR and should be unrelated.
The new test case for DateOnly type passes.

**Comment by mamift** [comment]
I dont think you noticed but I updated the [master branch](https://github.com/mamift/LinqToXsdCore/commit/a0873c909164c0dafc102c9e7baf9f2dfa3944bf) while you were working on your PR.

Can you update your PR branch with the update to the master branch.

**Comment by mamift** [comment]
> Some tests fail but it looks like they were failing before my PR and should be unrelated. 

That does not seem to be the case at all; I run a public AzureDevOps build pipeline for this project:
https://dev.azure.com/mamift1/LinqToXsdCore/_build?definitionId=1&view=runs

At least 22 new failing tests and they all are directly related to your changes.

Compare [before (build 211)](https://dev.azure.com/mamift1/LinqToXsdCore/_build/results?buildId=211&view=results) with [after (build 217)](https://dev.azure.com/mamift1/LinqToXsdCore/_build/results?buildId=217&view=ms.vss-test-web.build-test-results-tab)

I'm looking into it further as I do know that some tests will now fail as you've updated the source code for those example schemas and those would not be related to your changes; but your does seem to have introduced some new bugs, just don't know which tests at the moment.

**Comment by mamift** [comment]
OK can you try to merge or incorporate [this branch](https://github.com/mamift/LinqToXsdCore/tree/test/mergetestPR52) into your PR branch? It's a test merge of your PR into master. You did introduce a small bug with code generation that affects some existing tests, and I believe I fixed most of the failling tests.

**Comment by jods4** [comment]
Hey sorry about that.

As at first glance the errors seemed unrelated, and the 3 last commits before my branch on March 12 had red ❌, I simply assumed it was failing. 

Looking into previous commits more carefully, it looks like they fail because of the non-compiling schema.

I'll try to take a more careful look over the weekend and fix things.

**Comment by jods4** [comment]
@mamift thanks for fixing one bug in test code.

The remaining bug was in tests only and caused by having a default config that includes `SplitCodeFiles` by `Namespace` even though it never was functional. I removed that default config (behavior remains identical as it was previously unimplemented).

Everything's green now.

**Review by mamift — APPROVED** [review]

**Pull request merged**
