### PR TITLE
Fix content model and enum related bugs.

### PR DESCRIPTION
**Pull request by rvuistin**
- Fix issue #37
- Fix issue #38
- Fix issue #31
- modernize build system
- migrate to `.NET 6`

I have added some unit tests in `ContentModelCodeGenTests`, `ContentModelRuntimeTests` and `EnumsCodeGenTest`

All tests are green and the code generated for a custom application which contains very complex schemas is now functional.

### CODE REVIEW

**Comment by mamift** [comment]
Hello, are you able to increment the version number in LinqToXsd/LinqToXsd.csproj?

**Comment by rvuistin** [comment]
Hi Muhamamd,
I'm still working on some `enum` issues. I hope to finish today.
I will increment the versions (`XObjectsCore` is concerned too) when I finish.
Roger

**Comment by mamift** [comment]
Ok sure.

**Comment by rvuistin** [comment]
Hi Muhammad,

That’s it for now.
The version (3.2.2) is now centralized in the `Version.props` file for all projects (see my last commit)

Some stuff to review...

**Comment by rvuistin** [comment]
The build scripts needed a refresh. It’s done.
- most properties are now centralized in the `Directory.Build.*` scripts.
- same for the version located in the `Version.props` script. If necessary, it can be overloaded in the project itself.

The LinqToXsd tool is now ready to be migrated to `net6`...

**Comment by mamift** [comment]
I'm happy with the changes. Ready to merge?

**Comment by rvuistin** [comment]
I have changed the `vmImage` to `windows-2022` in the `azure-pipelines.yml` to support `.NET6` but the check still fails.
Do you understand what's wrong with it ? I've never used azure pipelines before...

**Comment by rvuistin** [comment]
> I'm happy with the changes. Ready to merge?

Other than that this azure pipelines thing, yeah.

**Comment by mamift** [comment]
I was able to fix the pipeline issue, but was unable to run another rerun of the PR check for some reason.

**Pull request merged**
